=== Maldon112K/CAT1/prog1.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Company">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:integer" name="ID"/>
              <xs:element type="xs:string" name="NAME"/>
              <xs:element type="xs:integer" name="SALARY"/>
              <xs:element type="xs:string" name="EMAIL"/>
              <xs:element type="xs:integer" name="MobNum"/>
              <xs:element type="xs:string" name="Designation"/>
              <xs:element type="xs:integer" name="AGE"/>
              <xs:element type="xs:string" name="Promotion"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="unique">
      <xs:selector xpath="Employee"/>
      <xs:field xpath="ID"/>
 </xs:unique>
</xs:element>
<xs:simpleType name="custype">
<xs:restriction base="xs:integer">
<xs:minInclusive value="50000"></xs:minInclusive>
<xs:maxInclusive value="200000"></xs:maxInclusive>
</xs:restriction>
</xs:simpleType>
<xs:simpleType name="EMAIL"> 
    <xs:restriction base="xs:string"> 
      <xs:pattern value="[^@]+@[^\.]+\..+"/> 
    </xs:restriction> 
</xs:simpleType>
<xs:simpleType name="MobNum"> 
    <xs:restriction base="xs:string"> 
      <xs:pattern value="[2-9](([0-9]{6})|([0-9]{9}))" />
    </xs:restriction> 
</xs:simpleType>
  
</xs:schema>

=== Maldon112K/CAT1/prog1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='prog1.xsl'?>

<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="prog1.xsd">
<Employee>
<ID>1</ID>
<NAME>Maldon</NAME>
<SALARY>60000</SALARY>
<EMAIL>m@gmail.com</EMAIL>
<MobNum>5654789652</MobNum>
<Designation>intern</Designation>
<AGE>21</AGE>
<Promotion>Developer</Promotion>
  </Employee>
  <Employee>
<ID>2</ID>
<NAME>Alex</NAME>
<SALARY>70000</SALARY>
<EMAIL>a@gmail.com</EMAIL>
<MobNum>5475896565</MobNum>
<Designation>employee</Designation>
<AGE>55</AGE>
   
<Promotion>Manager</Promotion>
  </Employee>
  <Employee>
<ID>3</ID>
<NAME>Ash</NAME>
<SALARY>50000</SALARY>
<EMAIL>ash@gmail.com</EMAIL>
<MobNum>2312546589</MobNum>
<Designation>intern</Designation>
<AGE>21</AGE>

<Promotion>Developer</Promotion>

  </Employee>
  <Employee>
<ID>4</ID>
<NAME>Al</NAME>
<SALARY>60000</SALARY>
<EMAIL>al@gmail.com</EMAIL>
<MobNum>6569868547</MobNum>
<Designation>employee</Designation>
<AGE>54</AGE>
   
<Promotion>Associate Project Manager</Promotion>

  </Employee>
  <Employee>
<ID>5</ID>
<NAME>Neon</NAME>
<SALARY>80000</SALARY>
<EMAIL>ns@gmail.com</EMAIL>
<MobNum>5465898754</MobNum>
<Designation>employee</Designation>
<AGE>45</AGE>
    
<Promotion>Team Leader</Promotion>

  </Employee>
</Company>
